sudo: required
language: csharp
solution: AddressValidation.sln
script:
  - xbuild AddressValidation.sln
deploy:  
  provider: azure_web_apps
  username: jayakumar.shanmugam@verizon.com
  password: Jaishalu1!
  site: http://falcon21.azurewebsites.net